######### Cadastro Tópico
POST http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz

{
    "name": "Web1"
}

######### Listar todos os Tópico
GET http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz


######### Listar Tópico específico
GET http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz

######### Alterar Tópico
PUT http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz

{
    "name": "Web II"
}

######### Apagar Tópico
DELETE http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz
